# Generated by Django 6.0.5 on 2026-06-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0004_source_hash_full_md5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationentry',
            name='source_hash',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
